<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="10.4.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="10.3.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExaminationSystem.Domin\ExaminationSystem.Domin.csproj" />
  </ItemGroup>

</Project>
